myallegan/blueprints/page/views.py
from flask import Blueprint, render_template

page = Blueprint('page', __name__, template_folder='templates')


@page.route('/')
def home():
    return render_template('page/home.html')


@page.route('/terms')
def terms():
    return render_template('page/terms.html')


@page.route('/privacy')
def privacy():
    return render_template('page/privacy.html')

myallegan/templates/layouts/app.html
{% extends 'layouts/skeleton.html' %}

{% block header %}
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="{{ url_for('page.home') }}">
          <img src="{{ url_for('static', filename='images/my-allegan.jpg') }}"
               class="img-responsive"
               width="229" height="50" title="My Allegan" alt="My Allegan"/>
        </a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="#">Link Item</a></li>
        </ul>
      </div>
    </div>
  </nav>
{% endblock %}

{% block footer %}
  <li><a href="#">Contact</a></li>
  <li><a href="{{ url_for('page.privacy') }}">Privacy Policy</a></li>
  <li><a href="{{ url_for('page.terms') }}">Terms of Service</a></li>
{% endblock %}

myallegan/templates/layouts/skeleton.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description"
              content="{% block meta_description %}{% endblock %}">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{% block title %}{% endblock %}</title>

        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='styles/vendor/bootstrap.min.css') }}">
        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='styles/main.css') }}">
        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='styles/vendor/font-awesome.min.css') }}">
        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='styles/vendor/eonasdan-bootstrap-datetimepicker.4.13.30.min.css') }}">
        <script
            src="https://code.jquery.com/jquery-1.12.2.min.js"
            integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="
            crossorigin="anonymous"></script>

        {% if config['ANALYTICS_GOOGLE_UA'] %}
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

            ga('create', "{{ config['ANALYTICS_GOOGLE_UA'] }}", 'auto');
            ga('send', 'pageview');
        </script>
        {% endif %}
    </head>
    <body>
        {% block header %}{% endblock %}

        <main class="container-fluid">
            <div class="sm-margin-top">{% block heading %}{% endblock %}</div>
            {% block body %}{% endblock %}
        </main>

        <footer class="footer text-center">
            <div class="container">
                <ul class="list-inline">
                    <li class="text-muted">My Allegan &copy; 2016</li>
                    {% block footer %}{% endblock %}
                </ul>
            </div>
        </footer>

        <script
            src="{{ url_for('static', filename='scripts/vendor/bootstrap.min.js') }}">
        </script>
        <script
            src="{{ url_for('static', filename='scripts/vendor/moment.min.js') }}">
        </script>
        <script
            src="{{ url_for('static', filename='scripts/vendor/eonasdan-bootstrap-datetimepicker.4.14.30.min.js') }}">
        </script>
        <script
            src="{{ url_for('static', filename='scripts/main.js') }}">
        </script>
    </body>
</html>